import { Tajawal } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const tajawal = Tajawal({ weight: "500", subsets: ["arabic"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html dir="rtl" lang="ar">
      <body className={`${tajawal.className}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
